// ============================================
// PRODUCT CATALOG - College of Agriculture, Balaghat
// ============================================

const CATEGORIES = [
  { id: 'live', name: 'Live Cultures', icon: 'worm', color: '#8b6535' },
  { id: 'fert', name: 'Bio-Fertilizers', icon: 'compost', color: '#5e8c34' },
  { id: 'astra', name: 'Bio-Pesticides', icon: 'flask', color: '#c8542a' },
  { id: 'parni', name: 'Plant Extracts', icon: 'leaf', color: '#466d24' },
  { id: 'soil', name: 'Soil Boosters', icon: 'sprout', color: '#a8814d' },
  { id: 'gavya', name: 'Panchgavya', icon: 'cow', color: '#e8a838' },
];

const PRODUCTS = [
  // LIVE CULTURES
  {
    id: 'earthworm-1kg',
    cat: 'live',
    name: 'Eisenia Fetida Earthworms',
    short: 'Red Wiggler',
    desc: 'Premium composting earthworms from our college vermiculture unit. High reproduction rate, ideal for vermicompost production.',
    price: 800,
    unit: 'per kg',
    sizes: [{ label: '500 g', price: 450 }, { label: '1 kg', price: 800 }, { label: '5 kg', price: 3600 }],
    badge: 'Live',
    rating: 4.9,
    reviews: 124,
    stock: 'In Stock',
    color: '#8b6535',
    benefits: ['Converts waste 5x faster', 'Survives 5–35°C', 'Doubles every 60 days', 'Lab-certified strain'],
    usage: '1 kg of worms per 100 kg of organic waste in a vermibed.',
    composition: 'Live Eisenia fetida — 100% pure culture, 40,000+ worms/kg',
  },
  {
    id: 'bga-500g',
    cat: 'live',
    name: 'Blue-Green Algae (BGA)',
    short: 'Nitrogen-fixing biofertilizer',
    desc: 'Cyanobacteria culture for paddy fields. Fixes atmospheric nitrogen up to 30 kg/hectare/season.',
    price: 250,
    unit: 'per 500 g',
    sizes: [{ label: '500 g', price: 250 }, { label: '2 kg', price: 900 }],
    badge: 'Live',
    rating: 4.7,
    reviews: 56,
    stock: 'In Stock',
    color: '#466d24',
    benefits: ['Fixes 25–30 kg N/ha', 'Reduces urea by 25%', 'Improves grain yield 10–15%', 'Eco-friendly'],
    usage: '10 kg/hectare in standing water, one week after transplanting.',
    composition: 'Anabaena, Nostoc, Aulosira, Tolypothrix species',
  },

  // BIO-FERTILIZERS
  {
    id: 'vermicompost-5kg',
    cat: 'fert',
    name: 'Vermicompost',
    short: 'Black Gold',
    desc: 'Premium worm-cast manure rich in NPK, micronutrients, and beneficial microbes. Sieved & sun-cured.',
    price: 180,
    unit: 'per 5 kg',
    sizes: [{ label: '5 kg', price: 180 }, { label: '25 kg', price: 800 }, { label: '50 kg', price: 1500 }],
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 312,
    stock: 'In Stock',
    color: '#3a2916',
    benefits: ['NPK 1.6:0.7:0.8', 'Improves soil tilth', 'Slow-release nutrients', 'Disease suppression'],
    usage: '2–3 tonnes/hectare or 100 g/plant pot.',
    composition: 'N 1.6%, P 0.7%, K 0.8%, OC 18%, beneficial microbes 10⁹ CFU/g',
  },
  {
    id: 'vermiwash-1l',
    cat: 'fert',
    name: 'Vermiwash',
    short: 'Liquid worm tea',
    desc: 'Liquid extract collected from vermibeds. Foliar spray rich in enzymes, hormones & micronutrients.',
    price: 120,
    unit: 'per litre',
    sizes: [{ label: '1 L', price: 120 }, { label: '5 L', price: 500 }, { label: '20 L', price: 1800 }],
    badge: 'New Batch',
    rating: 4.8,
    reviews: 89,
    stock: 'In Stock',
    color: '#523a1f',
    benefits: ['Foliar nutrient boost', 'Plant immunity', 'Pest deterrent', 'Growth hormones'],
    usage: 'Dilute 1:10 with water. Spray on leaves at 15-day intervals.',
    composition: 'Auxins, cytokinins, gibberellins + trace elements',
  },

  // BIO-PESTICIDES (ASTRAS)
  {
    id: 'brahmastra-1l',
    cat: 'astra',
    name: 'Brahmastra',
    short: 'Broad-spectrum bio-pesticide',
    desc: 'Powerful natural pesticide from cow urine + 5 leaf extracts. Controls sucking pests, caterpillars, borers.',
    price: 220,
    unit: 'per litre',
    sizes: [{ label: '1 L', price: 220 }, { label: '5 L', price: 950 }],
    badge: 'Strong',
    rating: 4.8,
    reviews: 167,
    stock: 'In Stock',
    color: '#c8542a',
    benefits: ['Controls bollworm, mealybug', 'Safe for soil microbes', '7-day residual action', 'Zero chemical residue'],
    usage: 'Dilute 30 ml per litre water. Spray on infested crops.',
    composition: 'Desi cow urine + neem + custard apple + papaya + pomegranate + guava leaves',
  },
  {
    id: 'neemastra-1l',
    cat: 'astra',
    name: 'Neemastra',
    short: 'Daily-use mild pesticide',
    desc: 'Mild bio-pesticide for regular use. Controls aphids, jassids, whiteflies and small caterpillars.',
    price: 150,
    unit: 'per litre',
    sizes: [{ label: '1 L', price: 150 }, { label: '5 L', price: 650 }, { label: '20 L', price: 2400 }],
    rating: 4.7,
    reviews: 203,
    stock: 'In Stock',
    color: '#7fa84f',
    benefits: ['Daily prevention', 'No re-entry interval', 'Safe for pollinators', 'Cost-effective'],
    usage: '1 litre per 10 litres water. Spray every 10–15 days.',
    composition: 'Cow urine + cow dung + neem leaves & fruit pulp',
  },
  {
    id: 'agniastra-1l',
    cat: 'astra',
    name: 'Agniastra',
    short: 'Fire-strong pest killer',
    desc: 'Hottest bio-pesticide for severe infestations. Targets pod borers, stem borers and leaf folders.',
    price: 250,
    unit: 'per litre',
    sizes: [{ label: '1 L', price: 250 }, { label: '5 L', price: 1100 }],
    badge: 'Hot',
    rating: 4.9,
    reviews: 98,
    stock: 'In Stock',
    color: '#8b1a1a',
    benefits: ['Severe pest control', 'Fast knockdown', 'Long residual', 'Borer specialist'],
    usage: 'Dilute 25 ml per litre. Use only on severe outbreaks.',
    composition: 'Cow urine + tobacco + green chilli + garlic + neem leaves',
  },

  // PARNI (LEAF EXTRACTS)
  {
    id: 'panchparni-1l',
    cat: 'parni',
    name: 'Panchparni',
    short: '5-leaf decoction',
    desc: 'Traditional 5-herb leaf extract. Mild prophylactic against fungal & bacterial infections.',
    price: 180,
    unit: 'per litre',
    sizes: [{ label: '1 L', price: 180 }, { label: '5 L', price: 800 }],
    rating: 4.6,
    reviews: 71,
    stock: 'In Stock',
    color: '#5e8c34',
    benefits: ['Disease prevention', 'Boosts immunity', 'Safe for all crops', 'Traditional formulation'],
    usage: '500 ml in 15 L water. Spray every 15 days.',
    composition: 'Neem + custard apple + bel + karanj + dhatura leaves',
  },
  {
    id: 'astparni-1l',
    cat: 'parni',
    name: 'Astparni',
    short: '8-leaf super extract',
    desc: 'Enhanced 8-herb decoction. Stronger pest deterrent & disease resistance.',
    price: 230,
    unit: 'per litre',
    sizes: [{ label: '1 L', price: 230 }, { label: '5 L', price: 1000 }],
    rating: 4.7,
    reviews: 54,
    stock: 'In Stock',
    color: '#466d24',
    benefits: ['Wider pest spectrum', 'Antifungal action', 'Hormonal support', 'Dual action'],
    usage: '500 ml in 15 L water. Apply at flowering & fruiting stages.',
    composition: '8 leaves: neem, custard apple, bel, karanj, dhatura, papaya, guava, tulsi',
  },
  {
    id: 'dashparni-1l',
    cat: 'parni',
    name: 'Dashparni',
    short: '10-leaf master extract',
    desc: 'Most potent leaf-based formulation. Used for major crop protection cycles.',
    price: 280,
    unit: 'per litre',
    sizes: [{ label: '1 L', price: 280 }, { label: '5 L', price: 1250 }, { label: '20 L', price: 4500 }],
    badge: 'Premium',
    rating: 4.9,
    reviews: 88,
    stock: 'In Stock',
    color: '#36531d',
    benefits: ['Comprehensive protection', 'Long shelf life', 'Multi-pest control', 'Soil + foliar use'],
    usage: '500 ml in 15 L water for foliar; 1 L per acre via drip irrigation.',
    composition: '10 leaves + cow urine + cow dung — fermented 30 days',
  },

  // SOIL BOOSTERS
  {
    id: 'beejamrit-1l',
    cat: 'soil',
    name: 'Beejamrit',
    short: 'Seed treatment elixir',
    desc: 'Microbial seed treatment that protects seedlings from soil-borne fungi & promotes germination.',
    price: 140,
    unit: 'per litre',
    sizes: [{ label: '1 L', price: 140 }, { label: '5 L', price: 600 }],
    rating: 4.8,
    reviews: 142,
    stock: 'In Stock',
    color: '#a8814d',
    benefits: ['Seed protection', 'Faster germination', 'Stronger seedlings', 'Disease prevention'],
    usage: 'Coat 1 kg seeds with 50 ml. Air-dry before sowing.',
    composition: 'Cow dung + cow urine + lime + water + handful of farm soil',
  },
  {
    id: 'jeevamrit-5l',
    cat: 'soil',
    name: 'Jeevamrit',
    short: 'Living microbial culture',
    desc: 'Liquid microbial inoculant. Multiplies beneficial microbes in soil. ZBNF foundation.',
    price: 120,
    unit: 'per 5 litres',
    sizes: [{ label: '5 L', price: 120 }, { label: '20 L', price: 450 }, { label: '100 L', price: 2000 }],
    badge: 'ZBNF',
    rating: 4.9,
    reviews: 256,
    stock: 'In Stock',
    color: '#7fa84f',
    benefits: ['Soil microbe boost', 'Reduces fertilizer 50%', 'Improves CEC', 'Builds humus'],
    usage: '200 L per acre via drip / flood irrigation, every 15 days.',
    composition: 'Cow dung + cow urine + jaggery + besan + soil + water — fermented 7 days',
  },
  {
    id: 'amritpani-5l',
    cat: 'soil',
    name: 'Amrit Pani',
    short: 'Soil revitalizer',
    desc: 'Concentrated microbial booster for soil application. Builds organic matter quickly.',
    price: 160,
    unit: 'per 5 litres',
    sizes: [{ label: '5 L', price: 160 }, { label: '20 L', price: 580 }],
    rating: 4.6,
    reviews: 67,
    stock: 'In Stock',
    color: '#a3c279',
    benefits: ['Quick soil revival', 'Microbial diversity', 'Root growth boost', 'Easy to apply'],
    usage: '5 L per acre with irrigation water. Use weekly during cropping.',
    composition: 'Cow dung + cow urine + honey + ghee + water',
  },

  // PANCHGAVYA
  {
    id: 'panchgavya-1l',
    cat: 'gavya',
    name: 'Panchgavya',
    short: '5-cow product elixir',
    desc: 'Sacred 5-ingredient formulation. Plant tonic, growth promoter & disease resistor.',
    price: 200,
    unit: 'per litre',
    sizes: [{ label: '1 L', price: 200 }, { label: '5 L', price: 900 }, { label: '20 L', price: 3200 }],
    badge: 'Sacred',
    rating: 4.9,
    reviews: 189,
    stock: 'In Stock',
    color: '#e8a838',
    benefits: ['Plant growth tonic', 'Disease resistance', 'Improved photosynthesis', 'Enhanced flavour'],
    usage: '30 ml per litre water. Foliar spray every 15 days.',
    composition: 'Desi cow dung + urine + milk + curd + ghee + jaggery + banana + tender coconut',
  },
];

window.CATEGORIES = CATEGORIES;
window.PRODUCTS = PRODUCTS;
